{{ if .Values.datadog.apmEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "datadog.fullname" . }}
  labels:
    app: "{{ template "datadog.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ template "datadog.fullname" . }}
  ports:
  {{- if .Values.datadog.apmEnabled }}
  - port: 8126
    name: traceport
    protocol: TCP
    targetPort: 8126
  {{- end }}
{{ end }}
